const { Router } = require('express')
const backendrouter = require('./backend')
const express = require('express')
const router = express.Router()
const multer = require("./schema/multer")


router.post('/collegeregistrationform',backendrouter.collegeRegistraion)
router.post('/staffregistrationform',backendrouter.staffRegistration)
router.get('/getcollegeregistrationform/:id',backendrouter.getcollegeregistration)
router.delete('/deletecollegeregistration/:id',backendrouter.deletecollegeRegistration)
router.get('/approvecollegeregistration/:id',backendrouter.approvecollegeRegistration)
router.post('/login',backendrouter.login)
router.post('/addpost',backendrouter.addpost)
router.get('/getpost/:name',backendrouter.getpost)
router.post('/addcompany', multer.single('img'),backendrouter.addcompany)
router.get('/getcompany/:name',backendrouter.getcompany)
router.post('/addalumni', multer.single('img'),backendrouter.addalumni)
router.get('/getalumni/:name',backendrouter.getalumni)
router.post('/addclub', multer.single('img'),backendrouter.addclub)
router.get('/getclub/:name',backendrouter.getclub)
router.get('/getcollegename',backendrouter.getCollegename)
router.get('/getClubById/:id',backendrouter.getClubById)
module.exports = router